### PR TITLE
handle displayValue for range sliders

### LINKED ISSUE #39: Show handle value when using a range
Reported by user in #36

### PR DESCRIPTION
**Pull request by boogheta**
Hello there,
Great lib, I was looking for one that handles properly range sliders with two handles and this one does the trick, although I noticed the displayValue feature was not working in this specific case.
I looked it up in the code and it felt like it wasn't too complex to fix, so here's my proposal!
You can see it in action by running the storybook (edit: here's the autobuild one https://deploy-preview-119--d3-simple-slider.netlify.com/?path=/story/basic-functionality--range )
Best,

(this shall close #39)

### CODE REVIEW

**Comment by boogheta** [comment]
And btw, I was afraid by looking at the examples it would work only with d3 v5 while my project runs v4, but actually it works also with v4! (fyi if you didn't already know)

**Comment by johnwalley** [comment]
Ho @boogheta. Thanks for the PR!

I never enabled support for displayValue when using a range because I wasn't happy with the way the text would overlap when the handles got close. It's probably time to revisit that decision though. I'll take a proper look when I next get a chance.

A quick search did turn up this [example](http://ionden.com/a/plugins/ion.rangeSlider/demo.html#a_range) which merges the values into one when they get close.

Anyway, I'll get back to you shortly and thanks for letting me know about it working with v4. I'll add a note to the README about it 👍

**Comment by boogheta** [comment]
Hi, and indeed this is the last remnant bug with the feature, texts are still overlapping when moving the two handles too close together.
I guess it wouldn't be too complex to only keep the one being dragged using the same logic as in the ticksFadeOut function. Will see if I find an easy solution.
In the mean time I will use the adapted code of this PR for the zoom bar in my project here (currently in the v3 branch, but should be online soon) http://github.com/boogheta/coronavirus-countries (cf https://github.com/boogheta/coronavirus-countries/issues/21)

**Comment by boogheta** [comment]
Hello again @johnwalley, I just added a new commit to handle that overlapping issue in a similar manner that the example you pointed out.
You can try it here and there:
- for horizontal range https://deploy-preview-119--d3-simple-slider.netlify.com/?path=/story/basic-functionality--range
- and for vertical range https://deploy-preview-119--d3-simple-slider.netlify.com/?path=/story/basic-functionality--range (I added a story to the storybook to test it)

**Comment by RouxRC** [comment]
Thanks!

**Comment by boogheta** [comment]
Thanks!

**Pull request merged**
